config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # constraints ->(request) { request.env["warden"].admin == true } do
    mount Avo::Engine, at: Avo.configuration.root_path
  # end

  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  get 'subscription_status', to: 'subscriptions#status'

  resources :subscriptions, only: [:new, :create, :approve]

  resources :users

  resources :roles

  # Admin authentication routes
  resources :admins, only: [:create]

  get "admin", to: "admins#new"
  post "admin", to: "admins#create"
  
  resources :publications do
    member do 
      post 'cite'
    end
  end

  resources :comments do
    resources :replies
  end

  resources :relationships, only: [:create, :destroy]

  # Show user profile
  get 'profile', to: 'users#show', as: :user_profile
  
  get 'contact', to: 'contact#index'
  get 'publications', to: 'publications#index'
  get 'faqs', to: 'faqs#index'
  get 'pricing', to: 'pricing#index'
  get 'privacy', to: 'privacy#index'
  get 'terms', to: 'terms#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/citation.rb
class Citation < ApplicationRecord
  belongs_to :user
  belongs_to :publication

  include UniqueId
 
  self.primary_key = :id 
  before_create :generate_unique_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :publication

  include UniqueId
 
  self.primary_key = :id 
  before_create :generate_unique_id
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  belongs_to :status
  has_many :comments, dependent: :destroy
  has_many :citations, dependent: :destroy

  validates :title, presence: true
  validates :abstract, presence: true
  validates :content, presence: true

  include UniqueId
 
  self.primary_key = :id
  before_create :generate_unique_id

  def self.ransackable_associations(*)
    ['user']
  end

  def self.ransackable_attributes(*)
    %w[title abstract]
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
  validates :follower_id, uniqueness: { scope: :followed_id }
  validate :cannot_follow_self

  private

  def cannot_follow_self
    errors.add(:follower_id, "can't follow self") if follower_id == followed_id
  end
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
  belongs_to :user

  validates :content, presence: true

  include UniqueId
 
  self.primary_key = :id 
  before_create :generate_unique_id
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :publications
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :subscription_type

  include UniqueId
 
  self.primary_key = :id 
  before_create :generate_unique_id

  def active?
    approved && end_date >= Date.today
  end

  def expired?
    end_date < Date.today
  end
end

app/models/subscription_type.rb
class SubscriptionType < ApplicationRecord
  has_many :subscriptions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable

  has_one_attached :avatar
        
  has_many :publications, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :citations, dependent: :destroy
  belongs_to :role
  has_one :subscription

  include UniqueId
 
  self.primary_key = :id 
  before_create :generate_unique_id

  # Setup the association where a user has many following relationships
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  # Setup the association where a user has many follower relationships
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # Through relationships
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # Helper methods to follow and unfollow users
  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pricing_helper.rb
module PricingHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admins/new.html.erb
<div id="w-node-e589e84a-0ba8-c850-6ac1-a4c50ec4c3b3-bdf1cc2e" class="full-page-wrapper">
  <div class="center-card">
    <div class="text-box">
      <h1 class="heading h3">Admin Sign In</h1>
      <p>Welcome back, it's good to see you.</p>
    </div>
    <div class="spacer _16"></div>
    <%= form_for(:admin, url: admins_path) do |f| %>
      <div class="mb-3">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Enter your email" %>
      </div>
      <br>
      <div class="mb-3">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control", placeholder: "*******" %>
      </div>

      <div class="mb-3">
        <%= f.submit "Log in", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_auth_navbar.html.erb
<div
data-collapse="small"
data-animation="default"
data-duration="400"
data-easing="ease"
data-easing2="ease"
role="banner"
class="nav-bar w-nav"
>
<div class="nav-container w-container">
<div class="logo-div">
<%= link_to root_path,
  class:"footer-logo w-nav-brand w--current" do %>
  <%= image_tag ("https://res.cloudinary.com/dmyhendcr/image/upload/v1696385443/legit_uploads/legit_research-logos_transparent_h6jpix.png"), width: 80 %>
<% end %>
</div>
<nav role="navigation" class="nav-content w-nav-menu">
<div class="nav-menu">
<%= link_to "Pricing", pricing_path, class: "nav-link w-nav-link" %>
<%= link_to "FAQs", faqs_path, class: "nav-link w-nav-link" %>
<%= link_to "Publications", publications_path, class: "nav-link w-nav-link" %>
<%= link_to "Contact", contact_path, class: "nav-link w-nav-link" %>
<div data-hover="true" data-delay="0" class="dropdown w-dropdown">
  <div class="nav-dropdown w-dropdown-toggle">
  </div>
  <nav class="dropdown-list w-dropdown-list">
    <a href="/contact" class="nav-link w-dropdown-link">Contact</a>
    <a href="/admin/style-guide" class="nav-link w-dropdown-link"
      >Style Guide</a
    >
  </nav>
</div>
</div>
<% if current_user %>
    <section class="logged-in-user-section">
      <% if is_user_profile_complete %>
        <%= link_to "Write", new_publication_path %>
      <% else %>
        <%= link_to "Complete Registration" %>
      <% end %>
    </section>
<% else %>
  <div class="nav-cta-button-container">
    <div style="color: white !important"><%= link_to "Get started now", user_session_path, class: "nav-link primary w-nav-link" %></div>
  </div>
<% end %>
</nav>

<div class="menu-button w-nav-button">
  <img
    src="https://assets.website-files.com/6398008a5a4ad6e37cf1cc10/6398008a5a4ad66dc9f1cc3d_Grey%20Hamburger%20Icon.svg"
    loading="lazy"
    width="24"
    alt=""
    class="menu-icon"
  />
</div>
</div>
</div>