config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # constraints ->(request) { request.env["warden"].admin == true } do
    mount Avo::Engine, at: Avo.configuration.root_path
  # end

  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  get 'subscription_status', to: 'subscriptions#status'

  resources :subscriptions, only: [:new, :create, :approve]

  resources :users

  resources :roles

  # Admin authentication routes
  resources :admins, only: [:create]

  get "admin", to: "admins#new"
  post "admin", to: "admins#create"
  
  resources :publications do
    member do 
      post 'cite'
    end
  end

  resources :comments do
    resources :replies
  end

  resources :relationships, only: [:create, :destroy]

  # Show user profile
  get 'profile', to: 'users#show', as: :user_profile
  
  get 'contact', to: 'contact#index'
  get 'publications', to: 'publications#index'
  get 'faqs', to: 'faqs#index'
  get 'pricing', to: 'pricing#index'
  get 'privacy', to: 'privacy#index'
  get 'terms', to: 'terms#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/citation.rb
class Citation < ApplicationRecord
  belongs_to :user
  belongs_to :publication

  include UniqueId
 
  self.primary_key = :id 
  before_create :generate_unique_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :publication

  include UniqueId
 
  self.primary_key = :id 
  before_create :generate_unique_id
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  belongs_to :status
  has_many :comments, dependent: :destroy
  has_many :citations, dependent: :destroy

  validates :title, presence: true
  validates :abstract, presence: true
  validates :content, presence: true

  include UniqueId
 
  self.primary_key = :id
  before_create :generate_unique_id

  def self.ransackable_associations(*)
    ['user']
  end

  def self.ransackable_attributes(*)
    %w[title abstract]
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
  validates :follower_id, uniqueness: { scope: :followed_id }
  validate :cannot_follow_self

  private

  def cannot_follow_self
    errors.add(:follower_id, "can't follow self") if follower_id == followed_id
  end
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
  belongs_to :user

  validates :content, presence: true

  include UniqueId
 
  self.primary_key = :id 
  before_create :generate_unique_id
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :publications
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :subscription_type

  include UniqueId
 
  self.primary_key = :id 
  before_create :generate_unique_id

  def active?
    approved && end_date >= Date.today
  end

  def expired?
    end_date < Date.today
  end
end

app/models/subscription_type.rb
class SubscriptionType < ApplicationRecord
  has_many :subscriptions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable

  has_one_attached :avatar
        
  has_many :publications, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :citations, dependent: :destroy
  belongs_to :role
  has_one :subscription

  include UniqueId
 
  self.primary_key = :id 
  before_create :generate_unique_id

  # Setup the association where a user has many following relationships
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  # Setup the association where a user has many follower relationships
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # Through relationships
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # Helper methods to follow and unfollow users
  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/avo/publications_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::PublicationsController < Avo::ResourcesController
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  before_action :check_subscription, only: [:new, :create]

  def index
    @publications = Publication.where(status_id: 2).order(:created_at => :desc)
  end

  def show
  end

  def new
    @publication = Publication.new
  end

  def create
    @publication = Publication.new(publication_params)

    if @publication.save
      cited_publication = Publication.find_by(id: params[:publication][:id])
      Citation.create(publication_id: cited_publication.id, user_id: current_user.id) if cited_publication

      redirect_to user_profile_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @publication.update(publication_params)
      redirect_to publication_path(@publication), notice: 'Publication was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @publication.destroy
    redirect_to publications_path, notice: 'Publication was successfully destroyed.'
  end

  private
    def check_subscription
      return unless current_user

      subscription = current_user.subscription

      if subscription.nil?
        redirect_to new_subscription_path, alert: 'Please subscribe to access this content.'
      elsif !subscription.approved?
        redirect_to subscription_status_path, alert: 'Your subscription is pending approval.'
      elsif subscription.expired?
        redirect_to new_subscription_path, alert: 'Your subscription has expired.'
      end
    end

    def set_publication
      @publication = Publication.find(params[:id])
    end

    def publication_params
      params.require(:publication).permit(:title, :abstract, :content).merge(user_id: current_user.id, status_id: 1)
    end

    def authorize_user!
      redirect_to publications_path, alert: 'You are not authorized to perform this action.' unless @publication.user_id == current_user.id
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pricing_helper.rb
module PricingHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/publications/_publications.html.erb
<section class="publication-list-section">
  <% publications.each do |publication| %>
    <span><%= formattedDateTime(publication.created_at) %>, citations(<%= publication.citations.count %>)</span>
    <h4><%= link_to publication.title, publication_path(publication) %></h4>
    <p><%= publication.abstract %></p>
  <% end %>
</section>

app/views/publications/edit.html.erb
<%= render "layouts/navbar" %>

<section class="edit-publication" style="width: 45%; margin: 30px auto;">
  <%= form_for @publication, url: publication_path(@publication), method: :patch do |f| %>
    <% if @publication.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

        <ul>
        <% @publication.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= f.label :title %>
      <%= f.text_field :title, id: :publication_title, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :abstract %>
      <%= f.text_area :abstract, id: :publication_abstract, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :content %>
      <%= f.text_area :content, id: :publication_content, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.submit "Update Publication", class: "btn btn-primary" %>
    </div>
  <% end %>

  <%= link_to 'Back', publications_path %>
</section>

<%= render "layouts/navbar" %>

app/views/publications/index.html.erb
<%= render "layouts/navbar" %>

<section class="logged-in-user-profile">
  <% if @publications.length > 0 %>
    <%= render "publications/publications", publications: @publications %>
  <% else %>
    <h4>No publications yet. <%= link_to "Get started!", new_publication_path %></h4>
  <% end %>
</section>

<%= render "layouts/footer" %>

app/views/publications/new.html.erb
<%= render "shared/auth_navbar" %>

<section class="new-publication-section">
  <%= form_for @publication do |form| %>
    <div class="mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.select :id, Publication.all.collect { |p| [ p.title, p.id ] }, include_blank: "Select publication to cite", class: "custom-select" %>
    </div>

    <div class="mb-3">
      <%= form.label :abstract, class: "form-label" %>
      <%= form.text_area :abstract, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :content, class: "form-label" %>
      <%= form.text_area :content, class: "form-control"%>
    </div>

    <div class="mb-3">
      <%= form.submit "Publish", class: "btn btn-primary" %>
    </div>
  <% end %>
</section>

<%= render "layouts/footer" %>

app/views/publications/show.html.erb
<%= render "shared/auth_navbar" %>

<section class="publication-details-section">
  <h2><b><%= @publication.title %></b></h2>
  <div class="publication-user-details">
    <div>
      <% if current_user && current_user == @publication.user %>
        <span><%= link_to capitalize_string(@publication.user.full_name), user_path(@publication.user) %> | <%= formattedDateTime(@publication.created_at) %> | <%= link_to "Edit", edit_publication_path %> | <%= link_to "Delete", publication_path(@publication), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></span>
      <% else %>
        <span><%= link_to capitalize_string(@publication.user.full_name), user_path(@publication.user) %> | <%= formattedDateTime(@publication.created_at) %></span>
      <% end %>
    </div>
  </div>
  <hr>
  <b><h3>Abstract</h3></b>
  <p><%= @publication.abstract %></p>
  <br>
  <p><%= simple_format(@publication.content) %></p>
  <br>
  <%= render "comments/comment", publication: @publication %>
  <br>
  <%= render "comments/comments", comments: @publication.comments %>
</section>

<%= render "layouts/footer" %>